### ISSUE TITLE
Error when creating docker container with portainer

### ISSUE THREAD

**Issue by adamkahl** [maxpozdeev/mytinytodo-docker#2]
When deploying a stack with the following compose.yml:
```
volumes:
  html:
services:
  web:
    image: maxpozdeev/mytinytodo:1.7-apache
    ports:
      - 8081:80
    restart: always
    environment:
      - MTT_DB_TYPE=sqlite
    volumes:
      - html:/var/www/html
```

I get the following error when accessing https://local_ip:8081

Forbidden
You don't have permission to access this resource.

Apache/2.4.54 (Debian) Server at local_ip Port 80

Here is the log from the container:
`[Wed May 24 11:33:54.668641 2023] [autoindex:error] [pid 18] [client ######] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`
